### ISSUE TITLE
运行报错了 请问是什么问题

### ISSUE THREAD

**Issue by gongdananyou** [HCLonely/hexo-bilibili-bangumi#6]
INFO  Getting bilibili bangumis, please wait...
(node:4922) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at _callee2$ (/home/gongdananyou/Desktop/blog/new/node_modules/hexo-bilibili-bangumi/index.js:179:19)
    at tryCatch (/home/gongdananyou/Desktop/blog/new/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/gongdananyou/Desktop/blog/new/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/home/gongdananyou/Desktop/blog/new/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/gongdananyou/Desktop/blog/new/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/gongdananyou/Desktop/blog/new/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HCLonely** [comment]
node版本多少

**Comment by gongdananyou** [comment]
@HCLonely v8.10.0

**Comment by HCLonely** [comment]
需要更新一下node版本，或者等我明天更新插件

**Comment by gongdananyou** [comment]
@HCLonely 好的 等你更新之后我再试试

**Comment by gongdananyou** [comment]
@HCLonely 已经通过更新node解决了 谢谢
