### ISSUE TITLE
运行报错请问是什么问题？

### ISSUE THREAD

**Issue by lewamlyn** [HCLonely/hexo-bilibili-bangumi#8]
```
INFO  Getting bilibili bangumis, please wait...
(node:6976) UnhandledPromiseRejectionWarning: TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableSpread (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\helpers\nonIterableSpread.js:2:9)
    at _toConsumableArray (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\helpers\toConsumableArray.js:10:95)
    at _callee3$ (C:\Users\lenovo\Documents\Hexo\node_modules\hexo-bilibili-bangumi\index.js:264:70)
    at tryCatch (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\lenovo\Documents\Hexo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6976) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre cated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by HCLonely** [comment]
配置发一下

**Comment by lewamlyn** [comment]
```
bangumi:
  enable: false 
  vmid: 87375957
  title: '追番列表'
  quote: '老二次猿了'
  webp: false
  show: 1
  loading: '/img/loading.gif'
```

**Comment by HCLonely** [comment]
已修复，更新一下
